# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: sbo-capability
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/sbo-capability/plugin.go
  ldflags:
    - '-w'
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
- name_template: "halkyon_plugin_{{ .Os }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
